### ISSUE TITLE
nav error

### ISSUE THREAD

**Issue by banane** [ihoka-me/radiant-database-mailer-extension#1]
"/Users/anna/Sites/client1/vendor/extensions/database_mailer/database_mailer_extension.rb:22:in `activate': undefined method`nav' for " can't re-start server, nor run the radiant:extensions:migrate tasks. 

started up a new radiant instance, then ran the instructions to install this ext.

1- install will_paginate gem, paperclip gem
2- install database_mailer, mailer extensions
3- modify environments.rb
4- cancel and start server, get error message (same message on the rake:extensions migrate tasks)

Could me missing something simple. Not sure!

**Comment by cristi** [comment]
I'm guessing you're using Radiant 0.8.x version, and you dind't checked out the correct revision of database_mailer extension. What you need to do is
cd vendor/extensions/database_mailer
git checkout -b <some-local-branch> origin/0.8

let me know if this solves the problem

**Comment by banane** [comment]
Thanks Cristi for the quick response!

**Comment by cristi** [comment]
glad this works. closing the issue now

**Comment by banane** [comment]
actually, looks liek doing a rake radiant:extensions:mailer:migrate before installing the database_mailer extension was the solution. I did the .9 version (despite having 8.1) and it seems to be working with out that "nav" error. Just thinking the mailer creates that nav item, so that's why the db-mailer can't update it in the activate class.

**Comment by banane** [comment]
oh, dod the rake radiant:extensions:mailer:migrate, then restart the server, no error, then installed db-mailer, and didn't get that error, so that's why I think it was the issue.

**Comment by cristi** [comment]
yeah, you need to have the mailer extension up and running before installing and migrating db_mailer.

it's interesting that it works with the 0.9 version of db_mailer because the "nav" thing was added only in Radiant 0.9. But, glad to hear it works.

**Comment by banane** [comment]
OK you were right- I checked out the 0.8 version and got past that error. Note- the <branch> was vendor/extensions/0.8 (that took me a bit to figure out)
