### ISSUE TITLE
new error on rake: fastercsv

### ISSUE THREAD

**Issue by banane** [ihoka-me/radiant-database-mailer-extension#2]
==  AddDataColumns: migrating =================================================
rake aborted!
no such file to load -- fastercsv
- any ideas? 
  Thanks

**Comment by cristi** [comment]
gem install fastercsv   should do it

**Comment by banane** [comment]
ok, that and spreadsheet too. Thanks for the tips.

**Comment by cristi** [comment]
yeah, spreasheet too.

my pleasure.

closing issue
