### ISSUE TITLE
database mailer don't work with radiant 0.9.1

### ISSUE THREAD

**Issue by titofranco** [ihoka-me/radiant-database-mailer-extension#3]
I made all the steps you suggested with radiant 0.8.0 and it worked perfectly, but when I upgrade to radiant 0.9.1 and then after do it all over again and execute the last step:
rake radiant:extensions:database_mailer:migrate
I get this:
rake aborted!
wrong number of arguments (3 for 2)

I use rails 2.3.5, ruby 1.8.7 and mysql 5.1.37
Thanks

**Comment by vrdeepak87** [comment]
I got the same error message too. 
I tried with Radiant 0.9 and got this error.
I use rails 2.3.5, ruby 1.8.7 and mysql 5.0.75.
Thanks

**Comment by divineforest** [comment]
Had the same error. To fix it just change in database_mailer_externsion.rb
admin.nav["content"] << admin.nav_item(:database_mailer, "Database Mailer", "/admin/form_datas")

to

tab 'Content' do
  add_item 'Database Mailer', '/admin/form_datas'
end

Worked for me.

**Comment by danigb** [comment]
Thanks! It worked for me (but after I've got an error with Mysql and indexing text columns... I've removed the indexes too)
